### ISSUE TITLE
Potential shader issue

### ISSUE THREAD

**Issue by MaticBabnik** [cmdwtf/filter-9slice#1]
Plugin did not work out of the box for me on Linux (Arch, obs 30.1.2-2)
I fixed it by adding `.xyz` on the sampler (it returns a `float4`?).

https://github.com/cmdwtf/filter-9slice/blob/66a6cca1d357e56363ae0c0a73ac5fe3dc596c25/data/sliced.hlsl#L98

I have no idea if it's unique to my setup/os/gpu driver.

**Comment by nitz** [comment]
Hm interesting catch.

I would guess it's _probably_ a driver thing, but I can't really be sure, because I can't reproduce it locally haha.

I did go ahead and change the shader to actually just use the float4 returned from the sampler (so that the alpha channel can be used too,) so thanks for the find!
